def config = generateConfig()

config.project.defaults.artifactory.credentialsId = 'artifactory-docker'
config.pipeline.stages.checkout.credentialsId = 'codecommit-service-account-id'

config.pipeline.stages.checkout.command = { checkout scm }

config.pipeline.stages.publish.gradle = [tasks: ['build', 'artifactoryPublish']]

config.pipeline.stages.unitTest.enabled = true
config.pipeline.stages.quality.enabled = true
config.pipeline.stages.build.toolName = "gradle-6"
ciPipeline(config)
