#mars:
#  databases:
#  - database:
#    key: TX
#    url: jdbc:mysql://127.0.0.1:3306/flyway_schema_1
#    username: root
#    password: root
#    location: db/migration
#  - database:
#    key: LA
#    url: jdbc:mysql://127.0.0.1:3306/flyway_schema_2
#    username: root
#    password: root
#    location: db/migration